# This Docker Compose file sets up an Nginx service with the following configuration:
# 
# Services:
#   nginx:
#     - Uses the official Nginx image from Docker Hub.
#     - The container is named "mynginx".
#     - The container will restart automatically unless it is explicitly stopped.
#     - Maps port 8081 on the host to port 80 in the container.
#     - Mounts the local file `nginx.conf` to `/etc/nginx/nginx.conf` inside the container.
#     - Mounts the local directory `html` to `/usr/share/nginx/html` inside the container.
# 
# Volumes:
#   html:
#     - Uses the local driver to create a volume named "html".
services:
  nginx:
    image: nginx
    container_name: mynginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure this is a file
      - ./html:/usr/share/nginx/html  # Ensure this is a directory

volumes:
  html:
    driver: local